from __future__ import annotations

from ai_slop_cleaner.classifier import classify_records
from ai_slop_cleaner.scanner import scan_documents


def test_newer_spec_supersedes_older_spec(tmp_path) -> None:
    (tmp_path / "payment-spec-v1.md").write_text(
        "# Payment Spec\nThe API uses token auth.\n",
        encoding="utf-8",
    )
    (tmp_path / "payment-spec-v2.md").write_text(
        "# Payment Spec\nThe API uses OAuth.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    results_by_path = {result.path: result for result in results}
    assert results_by_path["payment-spec-v1.md"].category == "stale"
    assert results_by_path["payment-spec-v2.md"].category == "canonical"


def test_major_version_outranks_large_minor_version(tmp_path) -> None:
    (tmp_path / "payment-spec-v1.10.md").write_text(
        "# Payment Spec\nThe API uses token auth.\n",
        encoding="utf-8",
    )
    (tmp_path / "payment-spec-v2.md").write_text(
        "# Payment Spec\nThe API uses OAuth.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    results_by_path = {result.path: result for result in results}
    assert results_by_path["payment-spec-v1.10.md"].category == "stale"
    assert results_by_path["payment-spec-v2.md"].category == "canonical"


def test_no_heading_versioned_filenames_group_by_filename_not_first_line(tmp_path) -> None:
    (tmp_path / "payment-spec-v1.md").write_text(
        "The API uses token auth.\n",
        encoding="utf-8",
    )
    (tmp_path / "payment-spec-v2.md").write_text(
        "The API uses OAuth.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    results_by_path = {result.path: result for result in results}
    assert results_by_path["payment-spec-v1.md"].category == "stale"
    assert results_by_path["payment-spec-v2.md"].category == "canonical"


def test_generic_overview_headings_do_not_group_unrelated_files(tmp_path) -> None:
    (tmp_path / "billing").mkdir()
    (tmp_path / "search").mkdir()
    (tmp_path / "billing" / "overview-v1.md").write_text(
        "# Overview\nBilling uses invoices.\n",
        encoding="utf-8",
    )
    (tmp_path / "search" / "overview-v2.md").write_text(
        "# Overview\nSearch uses indexing.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "billing/overview-v1.md": "canonical",
        "search/overview-v2.md": "canonical",
    }


def test_generic_api_headings_do_not_group_unrelated_files(tmp_path) -> None:
    (tmp_path / "github.md").write_text(
        "# API\nGitHub integration endpoint notes.\n",
        encoding="utf-8",
    )
    (tmp_path / "slack.md").write_text(
        "# API\nSlack integration endpoint notes.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "github.md": "canonical",
        "slack.md": "canonical",
    }


def test_same_title_in_different_directories_does_not_group(tmp_path) -> None:
    (tmp_path / "frontend").mkdir()
    (tmp_path / "backend").mkdir()
    (tmp_path / "frontend" / "auth.md").write_text(
        "# Auth\nFrontend auth spec.\n",
        encoding="utf-8",
    )
    (tmp_path / "backend" / "auth.md").write_text(
        "# Auth\nBackend auth spec.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "backend/auth.md": "canonical",
        "frontend/auth.md": "canonical",
    }


def test_generated_boilerplate_becomes_low_value(tmp_path) -> None:
    (tmp_path / "summary.md").write_text(
        "# AI Summary\n"
        "This document summarizes the above content. "
        "It is a high-level overview generated by AI.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert results[0].path == "summary.md"
    assert results[0].category == "low_value"


def test_ai_summary_title_without_boilerplate_stays_canonical(tmp_path) -> None:
    (tmp_path / "summary.md").write_text(
        "# AI Summary\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert results[0].path == "summary.md"
    assert results[0].category == "canonical"


def test_valid_titled_spec_mentioning_generated_by_ai_stays_canonical(tmp_path) -> None:
    (tmp_path / "audit-spec.md").write_text(
        "# Audit Spec\n"
        "The audit log should include whether content was generated by AI.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert results[0].path == "audit-spec.md"
    assert results[0].category == "canonical"


def test_valid_ai_summary_export_spec_stays_canonical(tmp_path) -> None:
    (tmp_path / "ai-summary-export-spec.md").write_text(
        "# AI Summary Export Spec\n"
        "The export must include a generated-by field.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert results[0].path == "ai-summary-export-spec.md"
    assert results[0].category == "canonical"


def test_tiny_no_heading_no_frontmatter_file_becomes_low_value(tmp_path) -> None:
    (tmp_path / "scratch.md").write_text(
        "todo\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert results[0].path == "scratch.md"
    assert results[0].category == "low_value"


def test_direct_requirement_conflict_is_flagged(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\nThe product must support SSO.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\nThe product must not support SSO.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_capability_family_verbs_conflict_for_same_object(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\nThe product must support SSO.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\nThe product must not allow SSO.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_multi_sentence_direct_requirement_conflict_is_flagged(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\n"
        "The product must support SSO. It must include audit logs.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\n"
        "The product must not support SSO. It must include audit logs.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_multi_sentence_conflict_does_not_absorb_following_requirement(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\n"
        "The product must support SSO. It must include audit logs.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\n"
        "The product must not support SSO. It must include trace logs.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_multi_sentence_conflict_detects_later_requirement_clause(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\n"
        "The product must support SSO. It must include audit logs.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\n"
        "The product must support SSO. It must not include audit logs.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_and_modal_boundary_does_not_pollute_requirement_object(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\n"
        "The product must support SSO and must include audit logs.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\n"
        "The product must not support SSO.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_trailing_non_requirement_sentence_does_not_pollute_requirement_object(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\n"
        "The product must support SSO. Migration note.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\n"
        "The product must not support SSO. Security decision.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_trailing_customer_sentence_after_requirement_still_conflicts(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\n"
        "The product must support SSO. Customers use it daily.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\n"
        "The product must not support SSO. Customers use password login.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }


def test_shared_sso_prefix_does_not_conflict_distinct_objects(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\nThe product must support SSO login.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\nThe product must not support SSO export.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert all(result.category != "conflict" for result in results)


def test_direct_requirement_conflict_ignores_modality(tmp_path) -> None:
    (tmp_path / "auth-a.md").write_text(
        "# Auth\nThe product must support SSO.\n",
        encoding="utf-8",
    )
    (tmp_path / "auth-b.md").write_text(
        "# Auth\nThe product should not support SSO.\n",
        encoding="utf-8",
    )

    results = classify_records(scan_documents(tmp_path))

    assert {result.path: result.category for result in results} == {
        "auth-a.md": "conflict",
        "auth-b.md": "conflict",
    }
