from __future__ import annotations

from collections import defaultdict
import re
from pathlib import PurePosixPath

from ai_slop_cleaner.models import ClassificationResult, DocumentRecord


CANONICAL_FILENAME_HINTS = ("final", "current", "latest")
NON_CANONICAL_FILENAME_HINTS = ("copy", "draft", "old")
DOCUMENT_KEY_STOP_TOKENS = {
    "copy",
    "current",
    "draft",
    "final",
    "latest",
    "old",
}
GENERIC_DOCUMENT_TITLES = {"api", "notes", "overview", "requirements", "spec", "summary"}
CAPABILITY_VERBS = {"allow", "enable", "support"}
LOW_VALUE_BOILERPLATE_PATTERNS = (
    "summarizes the above content",
    "high-level overview generated by ai",
)
LOW_VALUE_TINY_WORD_LIMIT = 3
REQUIREMENT_RE = re.compile(
    r"\b(?P<modality>must|should|shall)\s+"
    r"(?P<negation>not\s+)?"
    r"(?P<verb>support|include|use|require|allow|enable)\s+"
    r"(?P<object>[^.\n]+?)"
    r"(?=\s+and\s+(?:must|should|shall)\b|[.\n]|$)",
    re.IGNORECASE,
)
REQUIREMENT_BOUNDARY_SUBJECTS = {"and", "it", "this", "that"}
REQUIREMENT_MODALITIES = {"must", "should", "shall"}


def classify_records(records: list[DocumentRecord]) -> list[ClassificationResult]:
    results_by_path: dict[str, ClassificationResult] = {}
    hash_groups: dict[str, list[DocumentRecord]] = defaultdict(list)

    for record in records:
        if record.errors:
            results_by_path[record.relative_path] = ClassificationResult(
                path=record.relative_path,
                category="needs_review",
                confidence=1.0,
                signals=[{"name": "scanner_error", "errors": list(record.errors)}],
                reason="Scanner reported errors for this file.",
                errors=list(record.errors),
            )
            continue
        if record.hash is not None:
            hash_groups[record.hash].append(record)

    for group in hash_groups.values():
        if len(group) < 2:
            continue

        canonical = _choose_exact_hash_canonical(group)
        duplicate_paths = sorted(record.relative_path for record in group if record != canonical)
        results_by_path[canonical.relative_path] = ClassificationResult(
            path=canonical.relative_path,
            category="canonical",
            confidence=0.6,
            signals=[{"name": "default_canonical"}],
            reason="Selected as canonical representative for an exact hash group.",
            related_files=duplicate_paths,
        )

        for duplicate in group:
            if duplicate == canonical:
                continue
            results_by_path[duplicate.relative_path] = ClassificationResult(
                path=duplicate.relative_path,
                category="duplicate",
                confidence=0.99,
                signals=[
                    {
                        "name": "exact_hash_duplicate",
                        "canonical_path": canonical.relative_path,
                        "hash": duplicate.hash,
                    }
                ],
                reason=f"Exact content hash matches {canonical.relative_path}.",
                related_files=[canonical.relative_path],
            )

    for record in records:
        if record.relative_path in results_by_path:
            continue
        results_by_path[record.relative_path] = ClassificationResult(
            path=record.relative_path,
            category="canonical",
            confidence=0.6,
            signals=[{"name": "default_canonical"}],
            reason="No duplicate or review signals matched.",
        )

    _apply_low_value_rules(records, results_by_path)
    _apply_conflict_rules(records, results_by_path)
    _apply_stale_rules(records, results_by_path)

    return [results_by_path[path] for path in sorted(results_by_path)]


def _choose_exact_hash_canonical(records: list[DocumentRecord]) -> DocumentRecord:
    return min(records, key=_exact_hash_sort_key)


def _choose_canonical(records: list[DocumentRecord]) -> DocumentRecord:
    return min(records, key=_canonical_sort_key)


def _canonical_sort_key(record: DocumentRecord) -> tuple[int, int, int, float, int, str]:
    return (
        -_frontmatter_canonical_score(record),
        -_filename_hint_score(record),
        -_version_score(record),
        -record.mtime,
        -len(record.references),
        record.relative_path,
    )


def _exact_hash_sort_key(record: DocumentRecord) -> tuple[int, int, float, int, str]:
    return (
        -_frontmatter_canonical_score(record),
        -_filename_hint_score(record),
        -record.mtime,
        -len(record.references),
        record.relative_path,
    )


def _frontmatter_canonical_score(record: DocumentRecord) -> int:
    frontmatter = {
        key.lower(): value.lower()
        for key, value in record.frontmatter.items()
    }
    score = 0
    if frontmatter.get("status") in {"canonical", "current", "final"}:
        score += 3
    if frontmatter.get("canonical") in {
        "true",
        "yes",
        "1",
        "canonical",
        "current",
        "final",
    }:
        score += 4
    return score


def _filename_hint_score(record: DocumentRecord) -> int:
    name = record.relative_path.rsplit("/", maxsplit=1)[-1].lower()
    score = 0
    if any(hint in name for hint in CANONICAL_FILENAME_HINTS):
        score += 1
    if any(hint in name for hint in NON_CANONICAL_FILENAME_HINTS):
        score -= 1
    return score


def _apply_low_value_rules(
    records: list[DocumentRecord],
    results_by_path: dict[str, ClassificationResult],
) -> None:
    for record in records:
        if results_by_path[record.relative_path].category != "canonical":
            continue
        if not _is_low_value(record):
            continue
        results_by_path[record.relative_path] = ClassificationResult(
            path=record.relative_path,
            category="low_value",
            confidence=0.8,
            signals=[{"name": "low_value_content"}],
            reason="Generated summary boilerplate or tiny untitled content has low cleanup value.",
        )


def _apply_conflict_rules(
    records: list[DocumentRecord],
    results_by_path: dict[str, ClassificationResult],
) -> None:
    active_by_key: dict[str, list[DocumentRecord]] = defaultdict(list)
    for record in records:
        if results_by_path[record.relative_path].category != "canonical":
            continue
        active_by_key[_document_key(record)].append(record)

    for group in active_by_key.values():
        assertions_by_verb: dict[str, dict[bool, list[tuple[str, str]]]] = defaultdict(
            lambda: {False: [], True: []}
        )
        for record in group:
            for assertion in _requirement_assertions(record):
                _, verb, obj, negation = assertion
                if obj:
                    assertions_by_verb[_requirement_verb_key(verb)][negation].append(
                        (obj, record.relative_path)
                    )

        conflict_paths: set[str] = set()
        for polarities in assertions_by_verb.values():
            for positive_obj, positive_path in polarities[False]:
                for negative_obj, negative_path in polarities[True]:
                    if _requirement_objects_match(positive_obj, negative_obj):
                        conflict_paths.add(positive_path)
                        conflict_paths.add(negative_path)

        related = sorted(conflict_paths)
        for path in related:
            results_by_path[path] = ClassificationResult(
                path=path,
                category="conflict",
                confidence=0.9,
                signals=[{"name": "direct_requirement_contradiction"}],
                reason="Direct requirement statements contradict another file with the same document key.",
                related_files=[other for other in related if other != path],
            )


def _apply_stale_rules(
    records: list[DocumentRecord],
    results_by_path: dict[str, ClassificationResult],
) -> None:
    active_by_key: dict[str, list[DocumentRecord]] = defaultdict(list)
    for record in records:
        if results_by_path[record.relative_path].category != "canonical":
            continue
        active_by_key[_document_key(record)].append(record)

    for group in active_by_key.values():
        if len(group) < 2:
            continue
        canonical = _choose_canonical(group)
        canonical_version = _version_score(canonical)
        for record in group:
            if record == canonical:
                continue
            if _version_score(record) >= canonical_version and record.mtime >= canonical.mtime:
                continue
            results_by_path[record.relative_path] = ClassificationResult(
                path=record.relative_path,
                category="stale",
                confidence=0.85,
                signals=[
                    {
                        "name": "superseded_same_document_key",
                        "canonical_path": canonical.relative_path,
                    }
                ],
                reason=f"Superseded by newer canonical file {canonical.relative_path}.",
                related_files=[canonical.relative_path],
            )


def _document_key(record: DocumentRecord) -> str:
    title_key = _document_title_key(record)
    if title_key and _normalize_document_key_value(title_key) not in GENERIC_DOCUMENT_TITLES:
        value = title_key
    elif title_key:
        value = str(PurePosixPath(record.relative_path).with_suffix(""))
    else:
        value = PurePosixPath(record.relative_path).stem
    value = value.lower()
    value = re.sub(r"\b(?:v|version)[-_ ]*\d+(?:\.\d+)*\b", " ", value)
    value = re.sub(r"\b\d{4}[-_ ]?\d{2}[-_ ]?\d{2}\b", " ", value)
    value = re.sub(r"\b\d{8}\b", " ", value)
    tokens = re.findall(r"[a-z0-9]+", value)
    filtered = [token for token in tokens if token not in DOCUMENT_KEY_STOP_TOKENS]
    local_key = "".join(filtered) or PurePosixPath(record.relative_path).stem.lower()
    parent_key = _document_parent_key(record)
    return f"{parent_key}/{local_key}" if parent_key else local_key


def _document_parent_key(record: DocumentRecord) -> str:
    parent = PurePosixPath(record.relative_path).parent
    if str(parent) == ".":
        return ""
    tokens = re.findall(r"[a-z0-9]+", str(parent).lower())
    return "/".join(tokens)


def _document_title_key(record: DocumentRecord) -> str | None:
    frontmatter_title = record.frontmatter.get("title")
    if frontmatter_title:
        return frontmatter_title
    if record.headings:
        return record.headings[0]
    return None


def _normalize_document_key_value(value: str) -> str:
    tokens = re.findall(r"[a-z0-9]+", value.lower())
    return "".join(tokens)


def _is_low_value(record: DocumentRecord) -> bool:
    text = record.normalized_text.lower()
    if any(pattern in text for pattern in LOW_VALUE_BOILERPLATE_PATTERNS):
        return True
    return (
        not _document_title_key(record)
        and not record.frontmatter
        and len(text.split()) <= LOW_VALUE_TINY_WORD_LIMIT
    )


def _requirement_assertions(record: DocumentRecord) -> list[tuple[str, str, str, bool]]:
    assertions: list[tuple[str, str, str, bool]] = []
    for match in REQUIREMENT_RE.finditer(record.body_text.lower()):
        obj = _normalize_requirement_object(match.group("object"))
        assertions.append(
            (
                match.group("modality").lower(),
                match.group("verb").lower(),
                obj,
                bool(match.group("negation")),
            )
        )
    return assertions


def _requirement_verb_key(verb: str) -> str:
    if verb in CAPABILITY_VERBS:
        return "capability"
    return verb


def _normalize_requirement_object(value: str) -> str:
    tokens = re.findall(r"[a-z0-9-]+", value.lower())
    for index, token in enumerate(tokens):
        if token in REQUIREMENT_MODALITIES:
            tokens = tokens[:index]
            break
        if (
            token in REQUIREMENT_BOUNDARY_SUBJECTS
            and index + 1 < len(tokens)
            and tokens[index + 1] in REQUIREMENT_MODALITIES
        ):
            tokens = tokens[:index]
            break
    return " ".join(tokens)


def _requirement_objects_match(left: str, right: str) -> bool:
    if not left or not right:
        return False
    return left == right


def _version_score(record: DocumentRecord) -> int:
    for key in ("version", "doc_version"):
        value = record.frontmatter.get(key)
        if value:
            match = re.search(r"\d+(?:\.\d+)*", value)
            if match:
                return _version_tuple_to_int(match.group(0))

    name = PurePosixPath(record.relative_path).stem.lower()
    match = re.search(r"(?:^|[-_ .])v(?:ersion)?[-_ .]*(\d+(?:\.\d+)*)\b", name)
    if match:
        return _version_tuple_to_int(match.group(1))
    return 0


def _version_tuple_to_int(value: str) -> int:
    parts = [int(part) for part in value.split(".")]
    padded = (parts + [0, 0, 0])[:3]
    return padded[0] * 1_000_000 + padded[1] * 1_000 + padded[2]
